# Generated by Django 5.1.1 on 2024-09-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_superuser_user_is_staff_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_no',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Register Number'),
        ),
    ]
