# Generated by Django 5.1.1 on 2024-09-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='One Time Password'),
        ),
        migrations.DeleteModel(
            name='OneTimePassword',
        ),
    ]
