# Generated by Django 5.1.1 on 2024-09-16 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_otp_delete_onetimepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_no',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Register Number'),
        ),
    ]
