# Generated by Django 5.1.1 on 2024-09-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reset',
            field=models.BooleanField(default=False),
        ),
    ]
